question number 1

In [2]:
import numpy as np
import numpy.linalg as linear


def GramSchmidt(vectors):
    orthogonal_basis = np.zeros_like(vectors)
    for i in range(len(vectors)):
        orthogonal_basis[i] = vectors[i]
        for j in range(i):
            if (linear.norm(orthogonal_basis[j] != 0 )):
                orthogonal_basis[i] -= (np.dot(vectors[i], orthogonal_basis[j]) / np.dot(orthogonal_basis[j], orthogonal_basis[j])) * orthogonal_basis[j]
        size_of_base = linear.norm(orthogonal_basis[i])
        if (size_of_base != 0):
            orthogonal_basis[i] /= size_of_base
    return orthogonal_basis


.در این بخش تابع گرام-اشمیت پیاده شده است‌ 
نحوه کار بدین صورت است که ابتدا یک ماتریس صفر به اندازه ماتریسی که درون آن بردار های ما وجود دارد تولید میکنیم. سپس برای تولید بردار های یکه متعامد اولین بردار را به عنوان وی۱ انتخاب میکنیم سپس تمامی بردار های بعدی را بدین شکل تشکیل می‌دهیم که تمامی پروجکشن های بردار های متعامد قبلی از درون آن را خارج کنیم و در نهایت تمامی بردار ها را تبدیل به بردار یکه می‌کنیم‌

In [3]:

def is_in_subspace(vectors, new_vector):
    orthogonal_basis = GramSchmidt(vectors)
    print('here',orthogonal_basis)
    coefficients = np.dot(new_vector, orthogonal_basis.T)
    print("new vector : ",new_vector)
    print("T : ", orthogonal_basis.T)
    print("coefficients : " , coefficients)
    return np.allclose(np.dot(coefficients, orthogonal_basis), new_vector)


در این قسمت ابتدا بردار های ورودی را به تابع قسمت قبل می‌دهیم تا بردار های متعامد یکه را برایمان تولید کنند ‌
سپس برای تولید ضرایبی که احتمالا تولید کننده بردار مورد نظر ما باشند ، بردار مورد نظر را با ترانهاده بردار های متعامد یکه
ضرب می‌کنیم تا حاصل آن به صورت یک ماتریس که درونش ضرایب قرار دارند به ما برگردد ، صرفا در بخش آخر چک می‌کنیم آیا ‌‌
بردار حاصل با بردار اولیه برابر هستند یا نه

In [4]:

m = int(input())
input_arrays = []
for i in range(m):
    xi = input()
    xi_split = xi.split(' ')
    xi_split = [float(x) for x in xi_split]
    input_arrays.append(xi_split)
vectors = np.array(input_arrays)
print(vectors)

x_new = np.array([5,5,0])
booleanValue = is_in_subspace(vectors, x_new)
print(booleanValue) 

if (booleanValue) :
    print(GramSchmidt(vectors))
else :
    input_arrays.append([5.0,5.0,0.0])
    print("input array false :",input_arrays)
    new_vectors = np.array(input_arrays)
    print(GramSchmidt(new_vectors))

[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 2.]]
here [[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
new vector :  [5 5 0]
T :  [[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
coefficients :  [5. 5. 0.]
True
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


حال در بخش آخر کاری که می‌کنیم این است که چک کنیم آیا این بردار ساخته شده یا نه اگر نه، با اضافه کردن بردار مورد نظر به بردار های اولیه بردار های متعامد یکه آن رو تولید می‌کنیم و نمایش ‌می‌دهیم.